export 'alumni_model.dart';
export 'mahasiswa_model.dart';
export 'prodi_model.dart';
export 'jurusan_model.dart';
export 'detail_prodi_model.dart';
export 'fakultas_model.dart';
export 'matakuliah_model.dart';
export 'buku_ajar_model.dart';
export 'penelitian_model.dart';